/** Cloudflare Worker entry point for the value-investment application. */
// This module is generated by `opennextjs-cloudflare build`.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore The generated worker does not exist before the first build.
import handler from "../.open-next/worker.js";

const rateLimitKey = (request: Request) =>
  request.headers.get("CF-Connecting-IP") ?? "local-development";

async function rateLimitResponse(
  request: Request,
  env: CloudflareEnv,
): Promise<Response | null> {
  const pathname = new URL(request.url).pathname;
  const binding = pathname === "/api/screener"
    ? env.SCREENER_API_RATE_LIMITER
    : pathname.startsWith("/api/security/")
      ? env.SECURITY_API_RATE_LIMITER
      : null;
  if (!binding) return null;
  const { success } = await binding.limit({ key: rateLimitKey(request) });
  return success
    ? null
    : Response.json(
        {
          code: "RATE_LIMITED",
          error: "Too many analysis requests. Please wait before trying again.",
          retryable: true,
        },
        {
          status: 429,
          headers: { "Retry-After": "60" },
        },
      );
}

const worker = {
  async fetch(
    request: Request,
    env: CloudflareEnv,
    ctx: ExecutionContext,
  ): Promise<Response> {
    const limited = await rateLimitResponse(request, env);
    if (limited) return limited;
    return handler.fetch(request, env, ctx);
  },
  scheduled(
    controller: ScheduledController,
    env: CloudflareEnv,
    ctx: ExecutionContext,
  ): void {
    ctx.waitUntil(
      env.DB.prepare(
        "DELETE FROM anonymous_sessions WHERE expires_at <= ?",
      )
        .bind(controller.scheduledTime)
        .run(),
    );
  },
};

export default worker satisfies ExportedHandler<CloudflareEnv>;
